<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::pluck('id', 'slug');

        $products = [
            [
                'category_slug' => 'beds',
                'name_ar' => 'سرير فرعوني ملكي',
                'name_en' => 'Royal Pharaoh Bed',
                'description_ar' => 'سرير بتصميم فرعوني فاخر يضيف لمسة ملكية مميزة إلى غرفة النوم مع تفاصيل أنيقة وجودة عالية.',
                'description_en' => 'A luxurious pharaonic-style bed that adds a royal touch to any bedroom with elegant details and premium quality.',
                'price' => 450,
                'discount_price' => 399,
                'image' => 'uploads/products/beds/bed (1).jpeg',
                'gallery' => json_encode([
                    'uploads/products/beds/bed (8).jpeg',
                    'uploads/products/beds/bed (9).jpeg',
                    'uploads/products/beds/bed (10).jpeg',
                ]),
                'stock' => 10,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Beech Wood',
                'color' => 'Gold / Brown',
                'dimensions' => '200x180 cm',
                'rating' => 4.9,
            ],
            [
                'category_slug' => 'beds',
                'name_ar' => 'سرير فرعوني رومانسي',
                'name_en' => 'romantic Pharaoh Bed',
                'description_ar' => 'سرير بتصميم فرعوني فاخر يضيف لمسة رومانسية مميزة إلى غرفة النوم مع تفاصيل أنيقة وجودة عالية.',
                'description_en' => 'A luxurious pharaonic-style bed that adds a romantic touch to any bedroom with elegant details and premium quality.',
                'price' => 650,
                'discount_price' => 500,
                'image' => 'uploads/products/beds/bed (2).jpeg',
                'gallery' => json_encode([
                    'uploads/products/beds/bed (4).jpeg',
                    'uploads/products/beds/bed (5).jpeg',
                    'uploads/products/beds/bed (6).jpeg',
                ]),
                'stock' => 10,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Beech Wood',
                'color' => 'Gold / white',
                'dimensions' => '200x180 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'beds',
                'name_ar' => 'سرير فرعوني بسيط',
                'name_en' => 'romantic Pharaoh Bed',
                'description_ar' => 'سرير بتصميم فرعوني بسيط يضيف لمسة بسيطة مميزة إلى غرفة النوم مع تفاصيل أنيقة وجودة عالية.',
                'description_en' => 'A luxurious pharaonic-style bed that adds a simple touch to any bedroom with elegant details and premium quality.',
                'price' => 300,
                'discount_price' => 250,
                'image' => 'uploads/products/beds/bed (3).jpeg',
                'gallery' => json_encode([
                    'uploads/products/beds/bed (7).jpeg',
                    'uploads/products/beds/bed (12).jpeg',
                    'uploads/products/beds/bed (11).jpeg',
                ]),
                'stock' => 10,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Beech Wood',
                'color' => 'Gold / white',
                'dimensions' => '200x180 cm',
                'rating' => 4.2,
            ],
            [
                'category_slug' => 'beds',
                'name_ar' => 'سرير فرعوني جذاب',
                'name_en' => 'attractive Pharaoh Bed',
                'description_ar' => 'سرير بتصميم فرعوني بسيط يضيف لمسة جذابة مميزة إلى غرفة النوم مع تفاصيل أنيقة وجودة عالية.',
                'description_en' => 'A luxurious pharaonic-style bed that adds a attractive touch to any bedroom with elegant details and premium quality.',
                'price' => 700,
                'discount_price' => 500,
                'image' => 'uploads/products/beds/bed (4).jpeg',
                'gallery' => json_encode([
                    'uploads/products/beds/bed (1).jpeg',
                    'uploads/products/beds/bed (6).jpeg',
                    'uploads/products/beds/bed (2).jpeg',
                ]),
                'stock' => 10,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Beech Wood',
                'color' => 'Gold / white',
                'dimensions' => '200x180 cm',
                'rating' => 4.8,
            ],
            [
                'category_slug' => 'wardrobes',
                'name_ar' => 'دولاب فرعوني ذهبي',
                'name_en' => 'Golden Pharaoh Wardrobe',
                'description_ar' => 'دولاب مستوحى من الطراز الفرعوني يجمع بين العملية والفخامة بتفاصيل مميزة وتشطيب أنيق.',
                'description_en' => 'A pharaonic-inspired wardrobe that blends practicality and elegance with distinctive details and refined finishing.',
                'price' => 520,
                'discount_price' => 475,
                'image' => 'uploads/products/wardrobes/wardrobe (6).jpeg',
                'gallery' => json_encode([
                    'uploads/products/wardrobes/wardrobe (1).jpeg',
                    'uploads/products/wardrobes/wardrobe (2).jpeg',
                ]),
                'stock' => 7,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Oak Wood',
                'color' => 'Gold',
                'dimensions' => '220x180 cm',
                'rating' => 4.8,
            ],
            [
                'category_slug' => 'wardrobes',
                'name_ar' => 'دولاب فرعوني ازرق جذاب',
                'name_en' => 'attractive blue Pharaoh Wardrobe',
                'description_ar' => 'دولاب مستوحى من الطراز الفرعوني يجمع بين العملية والفخامة بتفاصيل مميزة ىورمز الجعران الفخم وتشطيب أنيق.',
                'description_en' => 'A pharaonic-inspired wardrobe that blends practicality and elegance with distinctive details and refined finishing.',
                'price' => 200,
                'discount_price' => 105,
                'image' => 'uploads/products/wardrobes/wardrobe (4).jpeg',
                'gallery' => json_encode([
                    'uploads/products/wardrobes/wardrobe (3).jpeg',
                    'uploads/products/wardrobes/wardrobe (5).jpeg',
                ]),
                'stock' => 7,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Oak Wood',
                'color' => 'Gold',
                'dimensions' => '220x180 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'wardrobes',
                'name_ar' => 'دولاب انيق برموز فرعونية',
                'name_en' => 'pharaonic wardrobe with pharaonic sybols',
                'description_ar' => 'دولاب مستوحى من الطراز الفرعوني يجمع بين العملية برموز عتيقة كمتاح الحياة وعين حورس غيرها من الرموز الساحرة الفخم وتشطيب أنيق.',
                'description_en' => 'A pharaonic-inspired wardrobe that blends practicality and elegance with ancient symbols like life key & eye of horus.',
                'price' => 350,
                'discount_price' => 300,
                'image' => 'uploads/products/wardrobes/wardrobe (5).jpeg',
                'gallery' => json_encode([
                    'uploads/products/wardrobes/wardrobe (7).jpeg',
                    'uploads/products/wardrobes/wardrobe (6).jpeg',
                ]),
                'stock' => 7,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Oak Wood',
                'color' => 'Gold',
                'dimensions' => '220x180 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'wardrobes',
                'name_ar' => 'دولاب عين حورس',
                'name_en' => 'eye of horus wardrobe',
                'description_ar' => 'دولاب مستوحى من الطراز الفرعوني يجمع بين العملية برمز عين حورس اللتي تجعله فخم وتشطيب أنيق.',
                'description_en' => 'pharaonic wardrobe with eye of horus symbol that makes it pretty.',
                'price' => 100,
                'discount_price' => 85,
                'image' => 'uploads/products/wardrobes/wardrobe (2).jpeg',
                'gallery' => json_encode([
                    'uploads/products/wardrobes/wardrobe (7).jpeg',
                    'uploads/products/wardrobes/wardrobe (6).jpeg',
                ]),
                'stock' => 7,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Oak Wood',
                'color' => 'Gold',
                'dimensions' => '220x180 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'tables',
                'name_ar' => 'ترابيزة عرش فرعونية',
                'name_en' => 'Pharaoh Throne Table',
                'description_ar' => 'ترابيزة بتصميم فرعوني أنيق تضيف لمسة فريدة من الفخامة والتميز إلى أي مساحة.',
                'description_en' => 'An elegant pharaonic-style table that brings a unique sense of luxury and distinction to any space.',
                'price' => 260,
                'discount_price' => 225,
                'image' => 'uploads/products/tables/table (6).jpeg',
                'gallery' => json_encode([
                    'uploads/products/tables/table (5).jpeg',
                    'uploads/products/tables/table (3).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Wood / Marble',
                'color' => 'vanilla-latte',
                'dimensions' => '140x80 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'tables',
                'name_ar' => 'ترابيزة الملكة نفرتيتي',
                'name_en' => 'nefertiti table',
                'description_ar' => 'ترابيزة بتصميم فرعوني أنيق تضيف لمسة فريدة من الفخامة والتميز إلى أي مساحة.',
                'description_en' => 'An elegant pharaonic-style table that brings a unique sense of luxury and distinction to any space.',
                'price' => 300,
                'discount_price' => 225,
                'image' => 'uploads/products/tables/table (9).jpeg',
                'gallery' => json_encode([
                    'uploads/products/tables/table (1).jpeg',
                    'uploads/products/tables/table (2).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Wood / Marble',
                'color' => 'brown/blue',
                'dimensions' => '140x80 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'tables',
                'name_ar' => 'ترابيزة فرعونية فاخرة',
                'name_en' => 'pharaonic table',
                'description_ar' => 'ترابيزة بتصميم فرعوني أنيق تضيف لمسة فريدة من الفخامة والتميز إلى أي مساحة.',
                'description_en' => 'An elegant pharaonic-style table that brings a unique sense of luxury and distinction to any space.',
                'price' => 170,
                'discount_price' => 125,
                'image' => 'uploads/products/tables/table (4).jpeg',
                'gallery' => json_encode([
                    'uploads/products/tables/table (5).jpeg',
                    'uploads/products/tables/table (6).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Wood / Marble',
                'color' => 'vanilla-latte',
                'dimensions' => '140x80 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'tables',
                'name_ar' => 'ترابيزة فرعونية عالية الجودة',
                'name_en' => 'premuim quality pharaonic table',
                'description_ar' => 'ترابيزة بتصميم فرعوني أنيق تضيف لمسة فريدة من الفخامة والتميز إلى أي مساحة.',
                'description_en' => 'An elegant pharaonic-style table that brings a unique sense of luxury and distinction to any space.',
                'price' => 200,
                'discount_price' => 125,
                'image' => 'uploads/products/tables/table (7).jpeg',
                'gallery' => json_encode([
                    'uploads/products/tables/table (3).jpeg',
                    'uploads/products/tables/table (8).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Wood / Marble',
                'color' => 'brown/gold',
                'dimensions' => '140x80 cm',
                'rating' => 5,
            ],
            [
                'category_slug' => 'vases',
                'name_ar' => 'فازة الجعران الملكية',
                'name_en' => 'Royal scarab Vase',
                'description_ar' => 'فازة بلمسة فرعونية راقية مثالية لإضفاء جمال فني وطابع تاريخي جذاب على الديكور.',
                'description_en' => 'A refined pharaonic-style vase perfect for adding artistic beauty and a captivating historical touch to the decor.',
                'price' => 95,
                'discount_price' => 79,
                'image' => 'uploads/products/vases/vase (5).jpeg',
                'gallery' => json_encode([
                    'uploads/products/vases/vase (6).jpeg',
                    'uploads/products/vases/vase (7).jpeg',
                ]),
                'stock' => 20,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Ceramic',
                'color' => 'Black / Gold',
                'dimensions' => '45 cm',
                'rating' => 4.6,
            ],
            [
                'category_slug' => 'vases',
                'name_ar' => 'فازة  فرعونية رائعة',
                'name_en' => 'fantasting pharaonic vase',
                'description_ar' => 'فازة بلمسة فرعونية راقية مثالية لإضفاء جمال فني وطابع تاريخي جذاب على الديكور.',
                'description_en' => 'A refined pharaonic-style vase perfect for adding artistic beauty and a captivating historical touch to the decor.',
                'price' => 70,
                'discount_price' => 50,
                'image' => 'uploads/products/vases/vase (8).jpeg',
                'gallery' => json_encode([
                    'uploads/products/vases/vase (9).jpeg',
                    'uploads/products/vases/vase (10).jpeg',
                ]),
                'stock' => 20,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Ceramic',
                'color' => 'Blue / Gold',
                'dimensions' => '45 cm',
                'rating' => 4.6,
            ],
            [
                'category_slug' => 'vases',
                'name_ar' => 'فازة  فرعونية زجاجية',
                'name_en' => 'glass pharaonic vase',
                'description_ar' => 'فازة بلمسة فرعونية راقية مثالية لإضفاء جمال فني وطابع تاريخي جذاب على الديكور.',
                'description_en' => 'A refined pharaonic-style vase perfect for adding artistic beauty and a captivating historical touch to the decor.',
                'price' => 80,
                'discount_price' => 70,
                'image' => 'uploads/products/vases/vase (9).jpeg',
                'gallery' => json_encode([
                    'uploads/products/vases/vase (11).jpeg',
                    'uploads/products/vases/vase (10).jpeg',
                ]),
                'stock' => 20,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Glass',
                'color' => 'Blue / Gold',
                'dimensions' => '45 cm',
                'rating' => 4.6,
            ],
            [
                'category_slug' => 'vases',
                'name_ar' => 'فازة  فرعون',
                'name_en' => ' pharaon vase',
                'description_ar' => 'فازة بلمسة فرعونية راقية مثالية لإضفاء جمال فني وطابع تاريخي جذاب على الديكور.',
                'description_en' => 'A refined pharaonic-style vase perfect for adding artistic beauty and a captivating historical touch to the decor.',
                'price' => 100,
                'discount_price' => 90,
                'image' => 'uploads/products/vases/vase (11).jpeg',
                'gallery' => json_encode([
                    'uploads/products/vases/vase (3).jpeg',
                    'uploads/products/vases/vase (10).jpeg',
                ]),
                'stock' => 20,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'clay',
                'color' => 'vanilla-latte / Gold',
                'dimensions' => '45 cm',
                'rating' => 4.1,
            ],
            [
                'category_slug' => 'carpets',
                'name_ar' => 'سجادة الاهرامات',
                'name_en' => 'pyramids Carpet',
                'description_ar' => 'سجادة مستوحاة من الفن الفرعوني تضيف دفئًا وفخامة للمكان بألوان ونقوش جذابة.',
                'description_en' => 'A carpet inspired by pharaonic art that adds warmth and luxury through attractive colors and patterns.',
                'price' => 180,
                'discount_price' => 150,
                'image' => 'uploads/products/carpets/carpet (6).jpeg',
                'gallery' => json_encode([
                    'uploads/products/carpets/carpet (1).jpeg',
                    'uploads/products/carpets/carpet (2).jpeg',
                ]),
                'stock' => 8,
                'is_featured' => true,
                'is_antique' => false,
                'material' => 'Wool',
                'color' => 'Beige / Brown',
                'dimensions' => '200x300 cm',
                'rating' =>5,
            ],
            [
                'category_slug' => 'carpets',
                'name_ar' => 'سجادة النقوش الفرعونية',
                'name_en' => 'pharaonic symbols Carpet',
                'description_ar' => 'سجادة مستوحاة من الفن الفرعوني تضيف دفئًا وفخامة للمكان بألوان ونقوش جذابة.',
                'description_en' => 'A carpet inspired by pharaonic art that adds warmth and luxury through attractive colors and patterns.',
                'price' => 150,
                'discount_price' => 110,
                'image' => 'uploads/products/carpets/carpet (3).jpeg',
                'gallery' => json_encode([
                    'uploads/products/carpets/carpet (4).jpeg',
                    'uploads/products/carpets/carpet (5).jpeg',
                ]),
                'stock' => 8,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Wool',
                'color' => 'colorful',
                'dimensions' => '200x300 cm',
                'rating' =>4.5,
            ],
            [
                'category_slug' => 'carpets',
                'name_ar' => 'سجادة كبيرة الحجم',
                'name_en' => 'large Carpet',
                'description_ar' => 'سجادة مستوحاة من الفن الفرعوني تضيف دفئًا وفخامة للمكان بألوان ونقوش جذابة.',
                'description_en' => 'A carpet inspired by pharaonic art that adds warmth and luxury through attractive colors and patterns.',
                'price' => 300,
                'discount_price' => 250,
                'image' => 'uploads/products/carpets/carpet (5).jpeg',
                'gallery' => json_encode([
                    'uploads/products/carpets/carpet (8).jpeg',
                    'uploads/products/carpets/carpet (7).jpeg',
                ]),
                'stock' => 8,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Wool',
                'color' => 'brown',
                'dimensions' => '600x400 cm',
                'rating' =>5,
            ],
            [
                'category_slug' => 'carpets',
                'name_ar' => 'سجادة فرعونية ',
                'name_en' => 'pharaonic Carpet',
                'description_ar' => 'سجادة مستوحاة من الفن الفرعوني تضيف دفئًا وفخامة للمكان بألوان ونقوش جذابة.',
                'description_en' => 'A carpet inspired by pharaonic art that adds warmth and luxury through attractive colors and patterns.',
                'price' => 130,
                'discount_price' => 120,
                'image' => 'uploads/products/carpets/carpet (7).jpeg',
                'gallery' => json_encode([
                    'uploads/products/carpets/carpet (4).jpeg',
                    'uploads/products/carpets/carpet (6).jpeg',
                ]),
                'stock' => 8,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Wool',
                'color' => 'brown',
                'dimensions' => '200x50 cm',
                'rating' =>4,
            ],
            [
                'category_slug' => 'antiques',
                'name_ar' => 'ساعة فرعونية كبيرة',
                'name_en' => 'big pharaonic clock',
                'description_ar' => 'قطعة أنتيك فرعونية فريدة تعكس روح التاريخ وتضفي قيمة جمالية وثقافية على المكان.',
                'description_en' => 'A unique pharaonic antique piece that reflects the spirit of history and adds aesthetic and cultural value.',
                'price' => 400,
                'discount_price' => 299,
                'image' => 'uploads/products/antiques/antique (2).jpeg',
                'gallery' => json_encode([
                    'uploads/products/antiques/antique (1).jpeg',
                    'uploads/products/antiques/antique (3).jpeg',
                ]),
                'stock' => 22,
                'is_featured' => true,
                'is_antique' => true,
                'material' => 'metal',
                'color' => 'Sand / brown',
                'dimensions' => '3 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'antiques',
                'name_ar' => 'ابريق فرعوني',
                'name_en' => 'pharaonic kettle',
                'description_ar' => 'قطعة أنتيك فرعونية فريدة تعكس روح التاريخ وتضفي قيمة جمالية وثقافية على المكان.',
                'description_en' => 'A unique pharaonic antique piece that reflects the spirit of history and adds aesthetic and cultural value.',
                'price' => 30,
                'discount_price' => 15,
                'image' => 'uploads/products/antiques/antique (1).jpeg',
                'gallery' => json_encode([
                    'uploads/products/antiques/antique (22).jpeg',
                    'uploads/products/antiques/antique (13).jpeg',
                ]),
                'stock' => 22,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'clay',
                'color' => 'white/ brown',
                'dimensions' => '30 cm',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'antiques',
                'name_ar' => 'لوحة زيتية',
                'name_en' => 'oily painting',
                'description_ar' => 'قطعة أنتيك فرعونية فريدة تعكس روح التاريخ وتضفي قيمة جمالية وثقافية على المكان.',
                'description_en' => 'A unique pharaonic antique piece that reflects the spirit of history and adds aesthetic and cultural value.',
                'price' => 10,
                'discount_price' => 9,
                'image' => 'uploads/products/antiques/antique (8).jpeg',
                'gallery' => json_encode([
                    'uploads/products/antiques/antique (21).jpeg',
                    'uploads/products/antiques/antique (18).jpeg',
                ]),
                'stock' => 22,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'paper',
                'color' => 'blue/ brown',
                'dimensions' => '30 cm',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'antiques',
                'name_ar' => 'لوحة قماش',
                'name_en' => 'fabric painting',
                'description_ar' => 'قطعة أنتيك فرعونية فريدة تعكس روح التاريخ وتضفي قيمة جمالية وثقافية على المكان.',
                'description_en' => 'A unique pharaonic antique piece that reflects the spirit of history and adds aesthetic and cultural value.',
                'price' => 30,
                'discount_price' => 25,
                'image' => 'uploads/products/antiques/antique (17).jpeg',
                'gallery' => json_encode([
                    'uploads/products/antiques/antique (21).jpeg',
                    'uploads/products/antiques/antique (18).jpeg',
                ]),
                'stock' => 22,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'fabric',
                'color' => 'blue/ gold',
                'dimensions' => '25 cm',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'sofas',
                'name_ar' => 'كنبة فرعونية',
                'name_en' => 'pharaonic sofa',
                'description_ar' => 'كنبة عصرية بتراث فرعوني قديم ولون ذهبي جذاب  عليها رموز ونقوش فرعونية مثل عين حورس',
                'description_en' => 'modern sofa with old fashion design , have gold color and symbols like eye of horus.',
                'price' => 300,
                'discount_price' => 250,
                'image' => 'uploads/products/sofas/sofa (3).jpeg',
                'gallery' => json_encode([
                    'uploads/products/antiques/sofa (4).jpeg',
                    'uploads/products/antiques/sofa (5).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'fabric',
                'color' => 'blue/ gold',
                'dimensions' => '7 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'sofas',
                'name_ar' => 'كنبة نفرتيتي',
                'name_en' => 'nefertiti sofa',
                'description_ar' => 'كنبة عصرية بتراث فرعوني قديم ولون ذهبي جذاب  عليها رموز ونقوش فرعونية مثل راس الملكة نفرتيتي',
                'description_en' => 'modern sofa with old fashion design , have gold color and symbols like head of nefertiti queen.',
                'price' => 500,
                'discount_price' => 450,
                'image' => 'uploads/products/sofas/sofa (12).jpeg',
                'gallery' => json_encode([
                    'uploads/products/sofas/sofa (11).jpeg',
                    'uploads/products/sofas/sofa (10).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => true,
                'is_antique' => true,
                'material' => 'fabric',
                'color' => 'blue/ gold / vanilla-latte',
                'dimensions' => '4 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'sofas',
                'name_ar' => 'كنبة فرعونية بسيطة',
                'name_en' => 'simple pharaonic sofa',
                'description_ar' => 'كنبة عصرية بتراث فرعوني قديم ولون ابيض جذاب  عليها رموز ونقوش فرعونية مثل  مفناح الحياة والجعران',
                'description_en' => 'modern sofa with old fashion design , have gold color and symbols like scarab and life key.',
                'price' => 350,
                'discount_price' => 250,
                'image' => 'uploads/products/sofas/sofa (9).jpeg',
                'gallery' => json_encode([
                    'uploads/products/sofas/sofa (6).jpeg',
                    'uploads/products/sofas/sofa (7).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'fabric',
                'color' => 'blue/ gold / vanilla-latte',
                'dimensions' => '4 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'sofas',
                'name_ar' => 'كنبة حديثة',
                'name_en' => 'modern sofa',
                'description_ar' => 'كنبة عصرية بتراث فرعوني حديث ولون ابيض جذاب  ',
                'description_en' => 'modern sofa with modern fashion design.',
                'price' => 350,
                'discount_price' => 250,
                'image' => 'uploads/products/sofas/sofa (1).jpeg',
                'gallery' => json_encode([
                    'uploads/products/sofas/sofa (2).jpeg',
                    'uploads/products/sofas/sofa (3).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'fabric',
                'color' => 'blue/ gold / vanilla-latte',
                'dimensions' => '9 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'doors',
                'name_ar' => 'باب فرعوني',
                'name_en' => 'pharaonic door',
                'description_ar' => 'باب بتصميم فرعوني مميز يعطي لمسه جذابة ومريحة للعين مما يجعل البيت ملئ بالاصالة والبهجة',
                'description_en' => 'door with pharaonic designthat gives attractive effect that makes thw home full of fancy and eye comfortable',
                'price' => 350,
                'discount_price' => 250,
                'image' => 'uploads/products/doors/door (1).jpeg',
                'gallery' => json_encode([
                    'uploads/products/doors/door (2).jpeg',
                    'uploads/products/doors/door (3).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'wood',
                'color' => 'blue/ gold / vanilla-latte',
                'dimensions' => '3 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'doors',
                'name_ar' => 'باب عين حورس',
                'name_en' => 'eye of horus door',
                'description_ar' => 'باب بتصميم فرعوني مميز يعطي لمسه جذابة ومريحة للعين مما يجعل البيت ملئ بالاصالة والبهجة',
                'description_en' => 'door with pharaonic designthat gives attractive effect that makes thw home full of fancy and eye comfortable',
                'price' => 250,
                'discount_price' => 150,
                'image' => 'uploads/products/doors/door (5).jpeg',
                'gallery' => json_encode([
                    'uploads/products/doors/door (1).jpeg',
                    'uploads/products/doors/door (4).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'wood',
                'color' => 'blue/ gold / brown',
                'dimensions' => '3 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'doors',
                'name_ar' => 'باب فرعوني بسيط',
                'name_en' => 'simple pharaonic door',
                'description_ar' => 'باب بتصميم فرعوني مميز يعطي لمسه جذابة ومريحة للعين مما يجعل البيت ملئ بالاصالة والبهجة',
                'description_en' => 'door with pharaonic designthat gives attractive effect that makes thw home full of fancy and eye comfortable',
                'price' => 250,
                'discount_price' => 150,
                'image' => 'uploads/products/doors/door (3).jpeg',
                'gallery' => json_encode([
                    'uploads/products/doors/door (5).jpeg',
                    'uploads/products/doors/door (2).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => true,
                'is_antique' => true,
                'material' => 'wood',
                'color' => 'blue/ gold /vanilla-latte',
                'dimensions' => '3 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'doors',
                'name_ar' => 'باب فرعوني بسيط',
                'name_en' => 'simple pharaonic door',
                'description_ar' => 'باب بتصميم فرعوني مميز يعطي لمسه جذابة ومريحة للعين مما يجعل البيت ملئ بالاصالة والبهجة',
                'description_en' => 'door with pharaonic designthat gives attractive effect that makes thw home full of fancy and eye comfortable',
                'price' => 250,
                'discount_price' => 150,
                'image' => 'uploads/products/doors/door (2).jpeg',
                'gallery' => json_encode([
                    'uploads/products/doors/door (4).jpeg',
                    'uploads/products/doors/door (1).jpeg',
                ]),
                'stock' => 12,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'wood',
                'color' => 'blue/ gold ',
                'dimensions' => '3 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'curtains',
                'name_ar' => 'ستارة الملكة نفرتيتي',
                'name_en' => 'nefertiti curtain',
                'description_ar' => 'ستارة بنية ذات تصميم هادئ يعطي اناقه للمكان ويجعله مصري اصيل',
                'description_en' => 'brown curtain with calm design gives elegency to the place and make it very egyptian',
                'price' => 50,
                'discount_price' => 40,
                'image' => 'uploads/products/curtains/curtain (6).jpeg',
                'gallery' => json_encode([
                    'uploads/products/curtains/curtain (2).jpeg',
                    'uploads/products/curtains/curtain (3).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'cotton',
                'color' => 'brown/ gold ',
                'dimensions' => '2 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'curtains',
                'name_ar' => 'ستارة الجعران الفرعوني',
                'name_en' => 'scarab curtain',
                'description_ar' => 'ستارة بيضاء ذات تصميم هادئ يعطي اناقه للمكان ويجعله مصري اصيل',
                'description_en' => 'vanilla-latte curtain with calm design gives elegency to the place and make it very egyptian',
                'price' => 50,
                'discount_price' => 40,
                'image' => 'uploads/products/curtains/curtain (1).jpeg',
                'gallery' => json_encode([
                    'uploads/products/curtains/curtain (4).jpeg',
                    'uploads/products/curtains/curtain (5).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'cotton',
                'color' => 'blue/ gold / vanilla-latte ',
                'dimensions' => '2 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'curtains',
                'name_ar' => 'ستارة الذهب الفرعوني',
                'name_en' => ' pharaonic gold curtain',
                'description_ar' => 'ستارة ذهبية ذات تصميم هادئ يعطي اناقه للمكان ويجعله مصري اصيل',
                'description_en' => 'golden curtain with calm design gives elegency to the place and make it very egyptian',
                'price' => 90,
                'discount_price' => 70,
                'image' => 'uploads/products/curtains/curtain (4).jpeg',
                'gallery' => json_encode([
                    'uploads/products/curtains/curtain (6).jpeg',
                    'uploads/products/curtains/curtain (7).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'cotton',
                'color' => 'blue/ gold ',
                'dimensions' => '2 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'curtains',
                'name_ar' => 'ستارة منقوشة',
                'name_en' => 'patterned curtain',
                'description_ar' => 'ستارة منقوشة ذات تصميم هادئ يعطي اناقه للمكان ويجعله مصري اصيل',
                'description_en' => 'patterned curtain with calm design gives elegency to the place and make it very egyptian',
                'price' => 90,
                'discount_price' => 70,
                'image' => 'uploads/products/curtains/curtain (9).jpeg',
                'gallery' => json_encode([
                    'uploads/products/curtains/curtain (8).jpeg',
                    'uploads/products/curtains/curtain (4).jpeg',
                ]),
                'stock' => 9,
                'is_featured' => false,
                'is_antique' => true,
                'material' => 'cotton',
                'color' => 'vanilla-latte/ gold ',
                'dimensions' => '2 m',
                'rating' => 5.0,
            ],
            [
                'category_slug' => 'mugs',
                'name_ar' => 'كوب اللوتس الأزرق الملكي',
                'name_en' => 'Royal Blue Lotus Mug',
                'description_ar' => 'كوب سيراميك فاخر يجمع بين اللون الأزرق الملكي وزخارف زهرة اللوتس المذهبة، يضيف لمسة ملوكية لمكتبك.',
                'description_en' => 'Premium ceramic mug featuring royal blue finish with gilded Lotus motifs, adding a regal touch to your desk.',
                'price' => 50,
                'discount_price' => 9,
                'image' => 'uploads/products/mugs/mug (2).jpeg',
                'gallery' => json_encode([
                    'uploads/products/mugs/ mug (1).jpeg',
                    'uploads/products/mugs/ mug (3).jpeg',
                ]),
                'stock' => 5,
                'is_featured' => false,
                'is_antique' => false,
                'material' => 'Ceramic',
                'color' => 'Blue & Gold',
                'dimensions' => '12x9x10',
                'rating' => 4.8,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'الكوب الذهبي المنقوش',
    'name_en' => 'Embossed Golden Deity Mug',
    'description_ar' => 'كوب مطلي بالذهب يبرز رموز السكاراب وعين حورس بنقوش بارزة وتصميم فريد يخطف الأنظار.',
    'description_en' => 'Gilded mug embossed with sacred Scarab and Eye of Horus symbols in a unique, eye-catching design.',
    'price' => 60,
    'discount_price' => 50,
    'image' => 'uploads/products/mugs/mug (3).jpeg',
    'gallery' => json_encode([]),
    'stock' => 4,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Porcelain',
    'color' => 'Brilliant Gold',
    'dimensions' => '12x9x10',
    'rating' => 5.0,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'كوب أجنحة إيزيس الصخري',
    'name_en' => 'Wings of Isis Stone Mug',
    'description_ar' => 'كوب بملمس صخري طبيعي يتميز بنحت يدوي ملون لأجنحة الإلهة إيزيس رمز الحماية.',
    'description_en' => 'Natural rock-textured mug featuring hand-painted relief of Goddess Isis wings, the symbol of protection.',
    'price' => 40,
    'discount_price' => 30,
    'image' => 'uploads/products/mugs/mug (4).jpeg',
    'gallery' => json_encode([]),
    'stock' => 25,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Stoneware',
    'color' => 'Bronze & Blue',
    'dimensions' => '12x9x11',
    'rating' => 4.7,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'كوب الرموز المقدسة الأبيض',
    'name_en' => 'White Sacred Symbols Mug',
    'description_ar' => 'كوب سيراميك أبيض أنيق مزين برموز عين حورس والسكاراب ومفتاح الحياة بتصميم عصري وبسيط.',
    'description_en' => 'Elegant white ceramic mug adorned with Eye of Horus, Scarab, and Ankh symbols in a modern minimalist design.',
    'price' => 28,
    'discount_price' => 15,
    'image' => 'uploads/products/mugs/mug (7).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => true,
    'is_antique' => false,
    'material' => 'Ceramic',
    'color' => 'White & Gold',
    'dimensions' => '11x8x10',
    'rating' => 4.5,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'كوب قناع توت عنخ آمون',
    'name_en' => 'King Tut Mask Mug',
    'description_ar' => 'كوب فريد يحمل نحت بارز ملون لقناع الملك توت عنخ آمون الذهبي على خلفية بنية كلاسيكية.',
    'description_en' => 'Unique mug featuring a colorful high-relief carving of King Tutankhamun\'s golden mask on a classic brown background.',
    'price' => 59,
    'discount_price' => 40,
    'image' => 'uploads/products/mugs/mug (1).jpeg',
    'gallery' => json_encode([]),
    'stock' => 40,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Resin-coated Ceramic',
    'color' => 'Brown & Gold',
    'dimensions' => '13x9x11',
    'rating' => 4.9,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'كوب مفتاح الحياة الذهبي',
    'name_en' => 'Golden Ankh Embossed Mug',
    'description_ar' => 'كوب مطلي بالذهب اللامع مع رموز مفتاح الحياة والسكاراب المنقوشة، يعطي طابعاً ملكياً لكل رشفة.',
    'description_en' => 'Brilliant gold-plated mug with embossed Ankh and Scarab symbols, providing a royal feel to every sip.',
    'price' => 62,
    'discount_price' => 50,
    'image' => 'uploads/products/mugs/mug (5).jpeg',
    'gallery' => json_encode([]),
    'stock' => 30,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Porcelain',
    'color' => 'Gold',
    'dimensions' => '12x9x10',
    'rating' => 5.0,
],
[
    'category_slug' => 'mugs',
    'name_ar' => 'كوب أبو الهول الملكي',
    'name_en' => 'Royal Sphinx Vessel',
    'description_ar' => 'كوب بتصميم برميلي يجمع بين ملمس الخشب والرخام مع تمثال أبو الهول الذهبي في المنتصف.',
    'description_en' => 'Barrel-style mug combining wood and marble textures with a golden Sphinx statue at the center.',
    'price' => 34,
    'discount_price' => 28,
    'image' => 'uploads/products/mugs/mug (6).jpeg',
    'gallery' => json_encode([]),
    'stock' => 20,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Composite Wood & Ceramic',
    'color' => 'Brown & Grey',
    'dimensions' => '14x10x12',
    'rating' => 4.9,
],
[
    'category_slug' => 'pots',
    'name_ar' => 'مقلاة حورس الذهبية',
    'name_en' => 'Golden Horus Frying Pan',
    'description_ar' => 'مقلاة طهي فاخرة مطلية بالذهب مع مقبض مزخرف ونقوش لعين حورس على الجوانب، قطعة ديكور وعملية في آن واحد.',
    'description_en' => 'Luxury gold-plated frying pan with an ornate handle and Horus eye engravings on the sides, both functional and decorative.',
    'price' => 110,
    'discount_price' => 106,
    'image' => 'uploads/products/pots/pot (5).jpeg',
    'gallery' => json_encode([]),
    'stock' => 15,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Non-stick Gilded Copper',
    'color' => 'Gold',
    'dimensions' => '24cm Diameter',
    'rating' => 4.8,
],
[
    'category_slug' => 'pots',
    'name_ar' => 'إناء الطهي الملكي',
    'name_en' => 'Royal Queen Cooking Pot',
    'description_ar' => 'إناء طهي عميق مزين بوجه ملكة مصرية وأعمدة فرعونية، يجمع بين الفن القديم واحتياجات المطبخ الحديث.',
    'description_en' => 'Deep cooking pot decorated with an Egyptian queen\'s face and pharaonic columns, blending ancient art with modern kitchen needs.',
    'price' => 70,
    'discount_price' => 60,
    'image' => 'uploads/products/pots/pot (2).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Cast Iron with Ceramic Finish',
    'color' => 'Brown & Gold',
    'dimensions' => '28cm Diameter',
    'rating' => 4.7,
],
[
    'category_slug' => 'pots',
    'name_ar' => 'إناء الجعران',
    'name_en' => 'scarab Cooking Pot',
    'description_ar' => 'إناء طهي عميق مزين برمز الجعران وأعمدة فرعونية، يجمع بين الفن القديم واحتياجات المطبخ الحديث.',
    'description_en' => 'Deep cooking pot decorated with an scarab and pharaonic columns, blending ancient art with modern kitchen needs.',
    'price' => 70,
    'discount_price' => 60,
    'image' => 'uploads/products/pots/pot (4).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Cast Iron with Ceramic Finish',
    'color' => 'blue & Gold',
    'dimensions' => '28cm Diameter',
    'rating' => 4.7,
],
[
    'category_slug' => 'pots',
    'name_ar' => 'إناء النقوش الفرعونية',
    'name_en' => ' pharaonic symbols Cooking Pot',
    'description_ar' => 'إناء طهي عميق مزين برموز فرعونية ، يجمع بين الفن القديم واحتياجات المطبخ الحديث.',
    'description_en' => 'Deep cooking pot decorated with an pharaonic symbols , blending ancient art with modern kitchen needs.',
    'price' => 62,
    'discount_price' => 50,
    'image' => 'uploads/products/pots/pot (1).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Cast Iron with Ceramic Finish',
    'color' => 'blue & Gold',
    'dimensions' => '28cm Diameter',
    'rating' => 4.7,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة الأفق الملكي المزدوجة',
    'name_en' => 'Royal Dual Horizon Mirror',
    'description_ar' => 'مرآة عرضية فاخرة بإطار مذهب يضم وجهين لملوك مصر القديمة مع نقوش زهرة اللوتس، تمنح المكان اتساعاً وفخامة لا مثيل لها.',
    'description_en' => 'Luxurious horizontal mirror with a gilded frame featuring two ancient Egyptian royal faces and Lotus engravings, offering unmatched spaciousness and elegance.',
    'price' => 200,
    'discount_price' => 150,
    'image' => 'uploads/products/mirrors/mirror (8).jpeg',
    'gallery' => json_encode([]),
    'stock' => 4,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Wood & Glass',
    'color' => 'Gold & white',
    'dimensions' => '120x70',
    'rating' => 5.0,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة بوابة الحياة',
    'name_en' => 'Ankh Portal Mirror',
    'description_ar' => 'مرآة بتصميم مبتكر يتوسطها رمز مفتاح الحياة (العنخ) الذهبي، محاطة بإطار منقوش برموز الحماية المصرية القديمة.',
    'description_en' => 'Innovatively designed mirror with a central golden Ankh symbol, surrounded by a frame engraved with ancient Egyptian protection symbols.',
    'price' => 100,
    'discount_price' => 80,
    'image' => 'uploads/products/mirrors/mirror (10).jpeg',
    'gallery' => json_encode([]),
    'stock' => 7,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Resin & Glass',
    'color' => 'Gold & brown',
    'dimensions' => '80x80',
    'rating' => 4.8,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة حارس الشمس المجنح',
    'name_en' => 'Winged Sun Guardian Mirror',
    'description_ar' => 'مرآة طولية ملكية يعلوها قرص الشمس المجنح، مع إطار مذهب بتفاصيل دقيقة تعكس فنون العصر الفرعوني الذهبي.',
    'description_en' => 'Vertical royal mirror topped with the winged sun disk, featuring a meticulously detailed gilded frame reflecting the golden Pharaonic era.',
    'price' => 200,
    'discount_price' => 150,
    'image' => 'uploads/products/mirrors/mirror (11).jpeg',
    'gallery' => json_encode([]),
    'stock' => 5,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Wood',
    'color' => 'Gold & blue',
    'dimensions' => '60x90',
    'rating' => 4.9,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة السكاراب الملكي الأزرق',
    'name_en' => 'Royal Blue Scarab Mirror',
    'description_ar' => 'مرآة دائرية بإطار ذهبي يعلوه سكاراب فيروزي مجنح، رمز الحظ والتجدد، مثالية لإضافة لمسة لونية وتاريخية.',
    'description_en' => 'Circular mirror with a golden frame topped by a turquoise winged scarab, the symbol of luck and rebirth, perfect for a historical touch.',
    'price' => 170,
    'discount_price' => 170,
    'image' => 'uploads/products/mirrors/mirror (6).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Polished Resin',
    'color' => 'Gold & Turquoise',
    'dimensions' => '70x70',
    'rating' => 4.7,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة خلود الأهرامات',
    'name_en' => 'Eternal Pyramid Mirror',
    'description_ar' => 'مرآة فنية ضخمة تجسد مشهد الأهرامات مع ميزان العدالة والآلهة، قطعة ديكور فريدة تحكي قصة الخلود.',
    'description_en' => 'Massive artistic mirror depicting the Pyramids with the Scale of Justice and deities, a unique piece telling the story of eternity.',
    'price' => 80,
    'discount_price' => 30,
    'image' => 'uploads/products/mirrors/mirror (17).jpeg',
    'gallery' => json_encode([]),
    'stock' => 3,
    'is_featured' => true,
    'is_antique' => false,
    'material' => 'Carved Wood & Bronze',
    'color' => 'Bronze & Gold',
    'dimensions' => '100x100',
    'rating' => 5.0,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة أعمدة طيبة',
    'name_en' => 'Thebes Column Mirror',
    'description_ar' => 'مرآة بتصميم طولي مؤطرة بأعمدة المعابد المصرية يعلوها وجه ملكي مذهب بدقة متناهية.',
    'description_en' => 'Vertical mirror designed with Egyptian temple columns, topped with a highly detailed golden royal face.',
    'price' => 100,
    'discount_price' => 50,
    'image' => 'uploads/products/mirrors/mirror (2).jpeg',
    'gallery' => json_encode([]),
    'stock' => 6,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Resin',
    'color' => 'Blue & Brown',
    'dimensions' => '55x85',
    'rating' => 4.8,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة درع الفرعون',
    'name_en' => 'Pharaoh Shield Mirror',
    'description_ar' => 'مرآة دائرية مهيبة تشبه دروع الملوك، محاطة بنقوش هيروغليفية بارزة ووجه فرعوني في القمة.',
    'description_en' => 'Majestic circular mirror resembling royal shields, surrounded by raised hieroglyphic engravings and a pharaoh\'s face at the top.',
    'price' => 240,
    'discount_price' => 199,
    'image' => 'uploads/products/mirrors/mirror (14).jpeg',
    'gallery' => json_encode([]),
    'stock' => 8,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gold-leaf Wood',
    'color' => 'Gold , vanilla-latte',
    'dimensions' => '75x75',
    'rating' => 4.9,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة محاكمة ريشة ماعت',
    'name_en' => 'Maat Ritual Mirror',
    'description_ar' => 'مرآة مستطيلة تعرض مشهد محاكمة القلب أمام أنوبيس، قطعة كلاسيكية معتّقة تضفي هيبة على المكان.',
    'description_en' => 'Rectangular mirror displaying the heart trial scene before Anubis, a vintage classic piece adding prestige to the space.',
    'price' => 90,
    'discount_price' => 60,
    'image' => 'uploads/products/mirrors/mirror (13).jpeg',
    'gallery' => json_encode([]),
    'stock' => 4,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Solid Wood & Hand Paint',
    'color' => 'Dark Wood & Gold',
    'dimensions' => '90x65',
    'rating' => 4.9,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة مدخل المعبد',
    'name_en' => 'Temple Entrance Mirror',
    'description_ar' => 'تصميم يحاكي مداخل المعابد المصرية مع قرص الشمس المجنح في الأعلى وأعمدة جانبية منقوشة.',
    'description_en' => 'Design mimicking Egyptian temple entrances with the winged sun disk at the top and side engraved columns.',
    'price' => 100,
    'discount_price' => 60,
    'image' => 'uploads/products/mirrors/mirror (9).jpeg',
    'gallery' => json_encode([]),
    'stock' => 5,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Hand-carved Wood',
    'color' => 'Brown & Gold',
    'dimensions' => '80x110',
    'rating' => 5.0,
],
[
    'category_slug' => 'mirrors',
    'name_ar' => 'مرآة الشمس البيضاء الملكية',
    'name_en' => 'Royal White Sun Mirror',
    'description_ar' => 'مرآة باللون الكريمي الراقي مع لمسات ذهبية لقرص الشمس المجنح، تناسب الديكورات المودرن والكلاسيكية.',
    'description_en' => 'Elegant cream-colored mirror with golden touches of the winged sun disk, fits both modern and classic decors.',
    'price' => 180,
    'discount_price' => 50,
    'image' => 'uploads/products/mirrors/mirror (4).jpeg',
    'gallery' => json_encode([]),
    'stock' => 12,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Painted Resin',
    'color' => 'Cream & Gold',
    'dimensions' => '65x65',
    'rating' => 4.6,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'خاتم الفرعون الذهبي',
    'name_en' => 'Golden Pharaoh Ring',
    'description_ar' => 'خاتم من الذهب المصقول يحمل نحتاً دقيقاً لوجه فرعوني، يجمع بين القوة والأناقة التاريخية.',
    'description_en' => 'Polished gold ring featuring a detailed carving of a Pharaonic face, blending strength with historical elegance.',
    'price' => 20,
    'discount_price' => 12,
    'image' => 'uploads/products/accesories/accesory (3).jpeg',
    'gallery' => json_encode([]),
    'stock' => 15,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gold Plated Stainless Steel',
    'color' => 'Gold',
    'dimensions' => 'Adjustable',
    'rating' => 5.0,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'سوار مفتاح الحياة المرصع',
    'name_en' => 'Studded Ankh Bracelet',
    'description_ar' => 'سوار أنيق مرصع بأحجار الزركون مع رمز مفتاح الحياة في المنتصف، لإطلالة ملكية عصرية.',
    'description_en' => 'Elegant bracelet studded with Zircon stones featuring the Ankh symbol at the center, for a modern royal look.',
    'price' => 80,
    'discount_price' => 50,
    'image' => 'uploads/products/accesories/accesory (5).jpeg',
    'gallery' => json_encode([]),
    'stock' => 20,
    'is_featured' => true,
    'is_antique' => false,
    'material' => 'Silver 925 Gold Plated',
    'color' => 'Gold',
    'dimensions' => '18cm',
    'rating' => 4.8,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'قلادة الملكة نفرتيتي',
    'name_en' => 'Queen Nefertiti Pendant',
    'description_ar' => 'قلادة ذهبية كلاسيكية تحمل بروفايل الملكة نفرتيتي الشهير، رمز الجمال المصري القديم.',
    'description_en' => 'Classic golden necklace featuring the famous Queen Nefertiti profile, the symbol of ancient Egyptian beauty.',
    'price' => 80,
    'discount_price' => 70,
    'image' => 'uploads/products/accesories/accesory (8).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gold 18K Plated',
    'color' => 'Gold',
    'dimensions' => '45cm Chain',
    'rating' => 4.9,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'أقراط عين حورس الذهبية',
    'name_en' => 'Golden Horus Eye Earrings',
    'description_ar' => 'أقراط صغيرة مصممة على شكل عين حورس، ترمز للحماية والشفاء بتصميم بسيط وجذاب.',
    'description_en' => 'Small stud earrings designed in the shape of the Eye of Horus, symbolizing protection and healing in a minimal design.',
    'price' => 20,
    'discount_price' => 18,
    'image' => 'uploads/products/accesories/accesory (16).jpeg',
    'gallery' => json_encode([]),
    'stock' => 30,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Stainless Steel',
    'color' => 'Gold',
    'dimensions' => '1cm',
    'rating' => 4.7,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'قلادة السكاراب المجنح',
    'name_en' => 'Winged Scarab Necklace',
    'description_ar' => 'قلادة مميزة بسكاراب ملون بأجنحة ممتدة، مستوحاة من المجوهرات الملكية المكتشفة في المقابر القديمة.',
    'description_en' => 'Distinctive necklace with a colorful scarab and extended wings, inspired by royal jewelry discovered in ancient tombs.',
    'price' => 350,
    'discount_price' => 310,
    'image' => 'uploads/products/accesories/accesory (10).jpeg',
    'gallery' => json_encode([]),
    'stock' => 8,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Enamel & Gold Plating',
    'color' => 'Multicolor & Gold',
    'dimensions' => '50cm Chain',
    'rating' => 5.0,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'بروش القطة باستيت',
    'name_en' => 'Bastet Cat Brooch',
    'description_ar' => 'دبوس صدر ذهبي يمثل الإلهة باستيت، مزين بتفاصيل دقيقة وحجر عقيق صغير.',
    'description_en' => 'Golden brooch representing Goddess Bastet, adorned with fine details and a small agate stone.',
    'price' => 50,
    'discount_price' => 30,
    'image' => 'uploads/products/accesories/accesory (7).jpeg',
    'gallery' => json_encode([]),
    'stock' => 12,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Zinc Alloy',
    'color' => 'Gold',
    'dimensions' => '4x2cm',
    'rating' => 4.6,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'خاتم النقوش الهيروغليفية',
    'name_en' => 'Hieroglyphic Band Ring',
    'description_ar' => 'خاتم عريض محفور عليه رموز هيروغليفية تحكي قصصاً من وادي الملوك.',
    'description_en' => 'A wide band ring engraved with hieroglyphic symbols telling stories from the Valley of the Kings.',
    'price' => 30,
    'discount_price' => 20,
    'image' => 'uploads/products/accesories/accesory (1).jpeg',
    'gallery' => json_encode([]),
    'stock' => 25,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Titanium Gold Plated',
    'color' => 'Gold',
    'dimensions' => 'All Sizes',
    'rating' => 4.8,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'خاتم زهرة اللوتس',
    'name_en' => 'Lotus Flower ring',
    'description_ar' => 'إكسسوار لليد بتصميم زهرة اللوتس المفتوحة، مرصع باللؤلؤ الصناعي لإطلالة ناعمة.',
    'description_en' => 'Hand accessory featuring an open Lotus flower design, studded with faux pearls for a soft look.',
    'price' => 90,
    'discount_price' => 75,
    'image' => 'uploads/products/accesories/accesory (6).jpeg',
    'gallery' => json_encode([]),
    'stock' => 40,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Brass & Faux Pearl',
    'color' => 'Gold & White',
    'dimensions' => '10cm',
    'rating' => 4.5,
],
[
    'category_slug' => 'accessories',
    'name_ar' => 'سوار العضد الثعباني',
    'name_en' => 'Golden Serpent Armlet',
    'description_ar' => 'سوار يلتف حول العضد على شكل ثعبان الكوبرا الملكي، رمز الحماية في مصر القديمة.',
    'description_en' => 'An upper arm bracelet in the shape of a royal cobra serpent, the symbol of protection in ancient Egypt.',
    'price' => 80,
    'discount_price' => 40,
    'image' => 'uploads/products/accesories/accesory (2).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => true,
    'is_antique' => false,
    'material' => 'Flexible Brass Gold Plated',
    'color' => 'Gold',
    'dimensions' => 'Adjustable',
    'rating' => 4.9,
],
[
    'category_slug' => 'plates',
    'name_ar' => 'طبق حورس الذهبي',
    'name_en' => 'Golden Horus Plate',
    'description_ar' => 'طبق تقديم فاخر مطلي بالذهب، مزين بنقوش عين حورس في المنتصف مع حواف مزخرفة بالهيروغليفية.',
    'description_en' => 'Luxury gold-plated serving plate, decorated with the Eye of Horus in the center and hieroglyphic embossed edges.',
    'price' => 450,
    'discount_price' => 399,
    'image' => 'uploads/products/plates/plate (12).jpeg',
    'gallery' => json_encode([]),
    'stock' => 25,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Gilded Ceramic',
    'color' => 'Gold',
    'dimensions' => '30cm',
    'rating' => 5.0,
],
[
    'category_slug' => 'plates',
    'name_ar' => 'طبق الملكة نفرتيتي',
    'name_en' => 'Queen Nefertiti Profile Plate',
    'description_ar' => 'طبق سيراميك يبرز بروفايل الملكة نفرتيتي بنقوش بارزة وألوان تحاكي الفخار المصري القديم.',
    'description_en' => 'Ceramic plate highlighting Queen Nefertiti\'s profile with embossed textures and colors mimicking ancient Egyptian pottery.',
    'price' => 380,
    'discount_price' => 320,
    'image' => 'uploads/products/plates/plate (13).jpeg',
    'gallery' => json_encode([]),
    'stock' => 15,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Terracotta Ceramic',
    'color' => 'Brown & Gold',
    'dimensions' => '25cm',
    'rating' => 4.8,
],
[
    'category_slug' => 'plates',
    'name_ar' => 'وعاء المعبد المذهب',
    'name_en' => 'Gilded Temple Bowl',
    'description_ar' => 'وعاء تقديم عميق محاط بأعمدة المعابد المصرية المذهبة، مثالي لتقديم الفواكه أو كقطعة ديكور.',
    'description_en' => 'Deep serving bowl surrounded by gilded Egyptian temple columns, perfect for fruits or as a decorative centerpiece.',
    'price' => 550,
    'discount_price' => 490,
    'image' => 'uploads/products/plates/plate (5).jpeg',
    'gallery' => json_encode([]),
    'stock' => 10,
    'is_featured' => true,
    'is_antique' => false,
    'material' => 'Porcelain & Gold Leaf',
    'color' => 'Cream & Gold',
    'dimensions' => '28cm',
    'rating' => 4.9,
],
[
    'category_slug' => 'plates',
    'name_ar' => 'طبق قناع توت عنخ آمون',
    'name_en' => 'King Tut Mask Serving Plate',
    'description_ar' => 'طبق تقديم ملكي يصور قناع الملك توت عنخ آمون باللونين الذهبي والأزرق الملكي.',
    'description_en' => 'Royal serving plate depicting King Tutankhamun\'s mask in brilliant gold and royal blue accents.',
    'price' => 420,
    'discount_price' => 380,
    'image' => 'uploads/products/plates/plate (9).jpeg',
    'gallery' => json_encode([]),
    'stock' => 20,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Fine Bone China',
    'color' => 'Gold & Blue',
    'dimensions' => '32cm',
    'rating' => 5.0,
],
[
    'category_slug' => 'plates',
    'name_ar' => 'إبريق زهرة اللوتس الصخري',
    'name_en' => 'Lotus Stone Pitcher',
    'description_ar' => 'إبريق ماء كلاسيكي بملمس حجري خشن ونقوش لزهرة اللوتس الزرقاء المقدسة.',
    'description_en' => 'Classic water pitcher with a rough stone texture and sacred blue Lotus flower engravings.',
    'price' => 600,
    'discount_price' => 540,
    'image' => 'uploads/products/plates/plate (16).jpeg',
    'gallery' => json_encode([]),
    'stock' => 12,
    'is_featured' => false,
    'is_antique' => true,
    'material' => 'Earthenware',
    'color' => 'Grey & Blue',
    'dimensions' => '25cm Height',
    'rating' => 4.6,
],

[
    'category_slug' => 'plates',
    'name_ar' => 'صينية قرص الشمس العظمى',
    'name_en' => 'Great Sun Disk Tray',
    'description_ar' => 'صينية تقديم كبيرة الحجم تتميز بنقش قرص الشمس المجنح المذهب، قطعة أساسية للولائم الملكية.',
    'description_en' => 'Large serving tray featuring the gilded winged sun disk engraving, an essential piece for royal banquets.',
    'price' => 750,
    'discount_price' => 680,
    'image' => 'uploads/products/plates/plate (14).jpeg',
    'gallery' => json_encode([]),
    'stock' => 8,
    'is_featured' => false,
    'is_antique' => false,
    'material' => 'Wood & Brass',
    'color' => 'Dark Brown & Gold',
    'dimensions' => '50cm',
    'rating' => 4.9,
],

        ];

        foreach ($products as $product) {
            Product::updateOrCreate(
                ['name_en' => $product['name_en']],
                [
                    'category_id' => $categories[$product['category_slug']] ?? null,
                    'name_ar' => $product['name_ar'],
                    'name_en' => $product['name_en'],
                    'description_ar' => $product['description_ar'],
                    'description_en' => $product['description_en'],
                    'price' => $product['price'],
                    'discount_price' => $product['discount_price'],
                    'image' => $product['image'],
                    'gallery' => $product['gallery'],
                    'stock' => $product['stock'],
                    'is_featured' => $product['is_featured'],
                    'is_antique' => $product['is_antique'],
                    'material' => $product['material'],
                    'color' => $product['color'],
                    'dimensions' => $product['dimensions'],
                    'rating' => $product['rating'],
                ]
            );
        }
    }
}